; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
platform_packages = 
	framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32#master
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = partitions.csv
board_build.flash_mode = dio
board_build.mcu = esp32c3
board_build.variant = esp32c3
lib_deps = 
	boblemaire/asyncHTTPrequest@^1.2.2
	me-no-dev/AsyncTCP@^1.1.1
	waspinator/AccelStepper@^1.61
	adafruit/Adafruit SSD1306@^2.5.3
build_flags = -D CORE_DEBUG_LEVEL=5
              -D DEBUG_ESP_HTTP_UPDATE

[env:wemos_d1_mini32]
platform = espressif32
board = wemos_d1_mini32
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
;board_build.mcu = esp32c3
;board_build.variant = esp32c3
board_build.partitions = partitions.csv
lib_deps = 
	boblemaire/asyncHTTPrequest@^1.2.2
	me-no-dev/AsyncTCP@^1.1.1
	waspinator/AccelStepper@^1.61
	adafruit/Adafruit SSD1306@^2.5.3
build_flags = -D CORE_DEBUG_LEVEL=5
              -D DEBUG_ESP_HTTP_UPDATE
;build_type = debug

[env:esp32dev]
platform = https://github.com/tasmota/platform-espressif32/releases/download/v2.0.2.1/platform-tasmota-espressif32-2.0.2.1.zip
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.flash_mode = dio
board_build.partitions = partitions.csv
board_build.mcu = esp32c3
board_build.variant = esp32c3
lib_deps = 
	boblemaire/asyncHTTPrequest@^1.2.2
	me-no-dev/AsyncTCP@^1.1.1
	waspinator/AccelStepper@^1.61
	adafruit/Adafruit SSD1306@^2.5.3
build_flags = -D CORE_DEBUG_LEVEL=5
              -D DEBUG_ESP_HTTP_UPDATE

[env:esp32c3]
# voor de ESPC3-WROOM-02V1.6
# van https://community.platformio.org/t/ai-thinker-esp32-c3-support-for-arduino-frameworks/22437/2
platform = espressif32
platform_packages =
	toolchain-riscv-esp
	framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git#master
	platformio/tool-esptoolpy @ ~1.30100
framework = arduino
; take usual esp32dev board and modify meta-info
; to make it a ESP32C3 board.
board = esp32dev
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.mcu = esp32c3
board_build.partitions = partitions.csv
board_build.variant = esp32c3
board_build.f_cpu = 160000000L
board_build.f_flash = 80000000L
board_build.flash_mode = dio
board_build.arduino.ldscript = esp32c3_out.ld
; remove old build flags
lib_deps = 
	boblemaire/asyncHTTPrequest@^1.2.2
	me-no-dev/AsyncTCP@^1.1.1
	waspinator/AccelStepper@^1.61
	adafruit/Adafruit SSD1306@^2.5.3
build_unflags =
  -DARDUINO_ESP32_DEV
  -DARDUINO_VARIANT="esp32"
; inject new ones 
; uncommont Serial macro below if serial is not working..
build_flags =
  -DARDUINO_ESP32C3_DEV
  -DARDUINO_VARIANT="esp32c3"
  -D CORE_DEBUG_LEVEL=5
  -D DEBUG_ESP_HTTP_UPDATE
;  -DARDUINO_SERIAL_PORT=1
;  -DBOARD_HAS_PSRAM
; -DCORE_DEBUG_LEVEL=5

[env:esp32dowdv3]
 # voor ESP32-WROOM-32E ofwel ESP32-DOWD-V3
# van https://community.platformio.org/t/ai-thinker-esp32-c3-support-for-arduino-frameworks/22437/2
platform = espressif32
framework = arduino
platform_packages = 
	framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32#master
; take usual esp32dev board and modify meta-info
;	platformio/tool-esptoolpy @ ~1.30100
board = esp32dev
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = partitions.csv
board_build.flash_mode = dio
; remove old build flags
lib_deps = 
	boblemaire/asyncHTTPrequest@^1.2.2
	me-no-dev/AsyncTCP@^1.1.1
	waspinator/AccelStepper@^1.61
	adafruit/Adafruit SSD1306@^2.5.3
build_unflags =
  -DARDUINO_ESP32_DEV
  -DARDUINO_VARIANT="esp32"
; inject new ones 
; uncommont Serial macro below if serial is not working..
build_flags = -D CORE_DEBUG_LEVEL=5
              -D DEBUG_ESP_HTTP_UPDATE
;build_type = debug

[env:airm2m_core_esp32c3]
# this is the environment used for esp32-c3-wroom-02 chip
platform = espressif32
board = airm2m_core_esp32c3
framework = arduino
board_build.partitions = partitions.csv
board_build.flash_mode = qio  # and NOT dio, otherwise Prefences won't work
monitor_speed = 115200
monitor_port = /dev/ttyUSB0
;monitor_port = /dev/ttyACM0
monitor_filters = esp32_exception_decoder
upload_port = /dev/ttyACM0
lib_deps = 
	boblemaire/asyncHTTPrequest@^1.2.2
	me-no-dev/AsyncTCP@^1.1.1
	waspinator/AccelStepper@^1.61
	adafruit/Adafruit SSD1306@^2.5.3
build_unflags =
  -DARDUINO_ESP32_DEV
  -DARDUINO_VARIANT="esp32"
; inject new ones 
; uncommont Serial macro below if serial is not working..
build_flags = -D CORE_DEBUG_LEVEL=5
              -D DEBUG_ESP_HTTP_UPDATE
